// One-off importer: Bing Maps scraper CSV → clean listing data.
//
//   node scripts/import-csv.mjs "<path-to.csv>"
//
// Filters to Georgia + spa categories (incl. "Beauty & spa"), de-dupes, maps
// fields to our model, groups by city, sorts by rating. Writes
// js/data/spas-imported.js (export const IMPORTED = [...]).
//
// NOTE: the scraper only has a single relative "Open Hours" string (not a weekly
// schedule), so imported spas get `hoursText` (display only) — NOT the weekly
// `hours` the live status needs. No black-owned / price data either.

import { readFileSync, writeFileSync } from 'node:fs';

const SRC = process.argv[2] || `${process.env.HOME}/Downloads/Bing_Maps_Scraper_224__20260531043644.csv`;

// included spa categories → our type
const TYPE_MAP = {
  'Spas': 'Day Spa',
  'Day spa': 'Day Spa',
  'Beauty & spa': 'Day Spa',
  'Medical spa': 'Med Spa',
  'Massage therapy': 'Massage',
};
const JUNK_EMAIL = /(stripe|zoca|chargebee|yelp|vagaro|twilio|microsoft|mixpanel|uxcam|moengage|imagekit|styleseat|clarity|@handandstone)/i;
const JUNK_LOCAL = /^(privacy|unsubscribe|webmaster|legal|info@stripe|people|hello@zoca|help|ir|support|dataprotection|quality|clarityms)/i;

const kebab = (s) => s.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// --- minimal RFC-4180 CSV parser ---
function parseCSV(text) {
  text = text.replace(/^﻿/, '');
  const rows = []; let row = [], field = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else q = false; }
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c === '\r') { /* skip */ }
    else field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const raw = parseCSV(readFileSync(SRC, 'utf8')).filter(r => r.length > 5);
const header = raw.shift();
const idx = Object.fromEntries(header.map((h, i) => [h.trim(), i]));
const get = (r, k) => (r[idx[k]] || '').trim();

const stats = { total: raw.length, nonGA: 0, nonSpa: 0, dupes: 0 };
const seen = new Set();
const out = [];

for (const r of raw) {
  const addr = get(r, 'Address');
  const state = addr.split(',').pop().trim().split(/\s+/)[0];
  if (state !== 'GA' && state !== 'Georgia') { stats.nonGA++; continue; }

  const cat = get(r, 'Category');
  const type = TYPE_MAP[cat];
  if (!type) { stats.nonSpa++; continue; }

  const key = (get(r, 'Name') + '|' + addr).toLowerCase();
  if (seen.has(key)) { stats.dupes++; continue; }
  seen.add(key);

  const parts = addr.split(',').map(s => s.trim());
  const cityName = parts.length >= 2 ? parts[parts.length - 2] : '';
  const zip = (addr.match(/\b(\d{5})\b/) || [])[1] || null;

  const rating = parseFloat(get(r, 'Rating')) || null;
  const reviews = parseInt((get(r, 'Rating Info').match(/\((\d+)\)/) || [])[1], 10) || null;

  let email = null;
  for (const e of get(r, 'Emails').split(',').map(s => s.trim())) {
    if (!e || e.includes('###') || JUNK_EMAIL.test(e) || JUNK_LOCAL.test(e)) continue;
    email = e; break;
  }

  out.push({
    id: kebab(get(r, 'Name') + '-' + cityName).slice(0, 60),
    name: get(r, 'Name'),
    city: kebab(cityName),
    cityName,
    type,
    tier: 'free',
    blackOwned: false,
    rating, reviews, zip,
    lat: parseFloat(get(r, 'Latitude')) || null,
    lng: parseFloat(get(r, 'Longitude')) || null,
    address: addr,
    phone: get(r, 'Phone') || null,
    website: get(r, 'Website') || null,
    email,
    image: get(r, 'Featured image') || null,
    hoursText: get(r, 'Open Hours') || null,
    facebook: get(r, 'Facebook') || null,
    instagram: get(r, 'Instagram') || null,
  });
}

// sort: city asc, then rating desc (nulls last), then reviews desc
out.sort((a, b) =>
  a.cityName.localeCompare(b.cityName) ||
  (b.rating ?? -1) - (a.rating ?? -1) ||
  (b.reviews ?? -1) - (a.reviews ?? -1));

writeFileSync(
  new URL('../js/data/spas-imported.js', import.meta.url),
  '// AUTO-GENERATED by scripts/import-csv.mjs — do not edit by hand.\n' +
  'export const IMPORTED = ' + JSON.stringify(out, null, 2) + ';\n'
);

// report
const byCity = {}, byType = {};
for (const s of out) { byCity[s.cityName] = (byCity[s.cityName] || 0) + 1; byType[s.type] = (byType[s.type] || 0) + 1; }
console.log(`Imported ${out.length} spas (of ${stats.total}).`);
console.log(`  dropped: ${stats.nonGA} non-GA, ${stats.nonSpa} non-spa, ${stats.dupes} dupes`);
console.log(`  types:`, byType);
console.log(`  cities:`);
for (const [c, n] of Object.entries(byCity).sort((a, b) => b[1] - a[1])) console.log(`    ${String(n).padStart(3)}  ${c}`);
console.log(`\nwrote js/data/spas-imported.js`);
